name: Collect election results data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Download and format the data
        run: |
          curl "https://results.lavote.gov/electionresults/json?electionid=4300" | jq > results.json
          curl "https://results.lavote.gov/ElectionResults/GetElectionData?electionID=4300" | jq > election_data.json
          curl "https://results.lavote.gov/ElectionResults/GetCounterData?electionID=4300" | jq ".Data|=sort_by(.Number)" > counter_data.json

      - name: Get a timestamp
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Commit results.json to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Latest results: ${{ env.timestamp }}"
          file_pattern: "*.json"
          skip_fetch: true
